const express = require('express');
const PDFDocument = require('pdfkit');
const User = require('../models/User');
const { auth, adminOnly } = require('../middleware/auth');
const router = express.Router();
function makePdf(user, month){return new Promise((resolve,reject)=>{const chunks=[];const doc=new PDFDocument();doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);doc.fontSize(20).text('Company Payslip').moveDown().fontSize(12).text(`Employee: ${user.name}`).text(`Employee ID: ${user.empId}`).text(`Department: ${user.department||'-'}`).text(`Month: ${month}`).moveDown().text('Generated by the Company Intranet Portal.');doc.end();});}
router.post('/send-whatsapp', auth, adminOnly, async(req,res)=>{try{const {month}=req.body;if(!month)return res.status(400).json({message:'month is required'});const users=await User.find({companyId:req.user.companyId,role:'employee'});const results=[];for(const user of users){const pdf=await makePdf(user,month);results.push({employeeId:user.empId,phone:user.phone||null,filename:`payslip-${month}-${user.empId}.pdf`,bytes:pdf.length,sent:false,reason:user.phone&&process.env.WHATSAPP_TOKEN?'WhatsApp provider adapter required at deployment':'Missing phone or WHATSAPP_TOKEN'});}res.json({total:results.length,configured:Boolean(process.env.WHATSAPP_TOKEN),results});}catch(e){res.status(500).json({message:e.message});}});
module.exports=router;
